### ISSUE TITLE
实现多扩展点，找不到实现方法

### ISSUE THREAD

**Issue by zhao-staff-officer** [alibaba/COLA#250]
你好，感谢COLA4.0给的分层架构设计。
对于Extnsion扩展麻烦指教一下。
```java
@Service
@RequiredArgsConstructor
public class LoginService  implements LoginFacade {

    private final ExtensionExecutor extensionExecutor;

    @Override
    public boolean loginAuth(LoginAuthDTO loginAuthDTO) {
        BizScenario bizScenario = BizScenario.valueOf(ConstantBizId.login,String.valueOf(loginAuthDTO.getLoginType()));
        LoginPo loginPo =extensionExecutor.execute(LoginParamsCoverExtPt.class,bizScenario, action->action.LogonCover(loginAuthDTO));
        extensionExecutor.execute(LoginParamsValidExtPt.class,bizScenario, action->action.validLoginParams(loginPo));
        return false;
    }
}
```java
```java
@Data
@Extension(bizId = ConstantBizId.login,useCase = ConstantCase.loginPwd)
public class LoginPwdPo extends LoginPo implements LoginParamsCoverExtPt, LoginParamsValidExtPt<LoginPwdPo> {

    /**
     * 用户名
     */
    private String userName;

    /**
     * 密码
     */
    private String pwd;


    /**
     * 对象转换
     * @param loginAuthDTO
     * @return
     */
    @Override
    public LoginPwdPo LogonCover(LoginAuthDTO loginAuthDTO) {
        return BeanUtil.toBean(loginAuthDTO, LoginPwdPo.class);
    }

    /**
     * 参数校验
     * @param loginPwdPo
     * @return
     */
    @Override
    public  boolean validLoginParams(LoginPwdPo loginPwdPo) {
        Assert.notEmpty(loginPwdPo.getUserName(),"用户名不为空");
        Assert.notEmpty(loginPwdPo.getPwd(),"密码不为空");
        return false;
    }

}
```java

异常
```
java.lang.RuntimeException: Can not find extension with ExtensionPoint: interface com.cloud.cola.domain.logindomain.interfacext.LoginParamsValidExtPt BizScenario:login.1.#defaultScenario#
	at com.alibaba.cola.extension.ExtensionExecutor.locateExtension(ExtensionExecutor.java:71) ~[cola-component-extension-starter-4.0.1.jar:na]
	at com.alibaba.cola.extension.ExtensionExecutor.locateComponent(ExtensionExecutor.java:31) ~[cola-component-extension-starter-4.0.1.jar:na]
	at com.alibaba.cola.extension.register.AbstractComponentExecutor.execute(AbstractComponentExecutor.java:26) ~[cola-component-extension-starter-4.0.1.jar:na]
	at com.cloud.cola.application.login.LoginService.loginAuth(LoginService.java:37) ~[classes/:na]
	at com.cloud.cola.adapter.LoginController.login(LoginController.java:34) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
```

一个类实现多扩展接口，在注入容器时候是否只会存在一个？

**Comment by zhao-staff-officer** [comment]
@Data
@Extension(bizId = ConstantBizId.login,useCase = ConstantCase.loginPwd)
public class LoginPwdPo extends LoginPo implements LoginParamsCoverExtPt, LoginParamsValidExtPt<LoginPwdPo> {

    /**
     * 用户名
     */
    private String userName;

    /**
     * 密码
     */
    private String pwd;


    /**
     * 对象转换
     * @param loginAuthDTO
     * @return
     */
    @Override
    public LoginPwdPo LogonCover(LoginAuthDTO loginAuthDTO) {
        System.out.println("对象转换");
        return BeanUtil.toBean(loginAuthDTO, LoginPwdPo.class);
    }

    /**
     * 参数校验
     * @param loginPwdPo
     * @return
     */
    @Override
    public  boolean validLoginParams(LoginPwdPo loginPwdPo) {
        System.out.println("对象校验");
        Assert.notEmpty(loginPwdPo.getUserName(),"用户名不为空");
        Assert.notEmpty(loginPwdPo.getPwd(),"密码不为空");
        return false;
    }

}

**Comment by zhao-staff-officer** [comment]
2021-11-27 17:03:47.920  INFO 13176 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 18 ms
对象转换
2021-11-27 17:03:57.301 ERROR 13176 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Can not find extension with ExtensionPoint: interface com.cloud.cola.domain.logindomain.interfacext.LoginParamsValidExtPt BizScenario:login.1.#defaultScenario#] with root cause

java.lang.RuntimeException: Can not find extension with ExtensionPoint: interface com.cloud.cola.domain.logindomain.interfacext.LoginParamsValidExtPt BizScenario:login.1.#defaultScenario#
	at com.alibaba.cola.extension.ExtensionExecutor.locateExtension(ExtensionExecutor.java:71) ~[cola-component-extension-starter-4.0.1.jar:na]
	at com.alibaba.cola.extension.ExtensionExecutor.locateComponent(ExtensionExecutor.java:31) ~[cola-component-extension-starter-4.0.1.jar:na]
	at com.alibaba.cola.extension.register.AbstractComponentExecutor.execute(AbstractComponentExecutor.java:26) ~[cola-component-extension-starter-4.0.1.jar:na]
	at com.cloud.cola.application.login.LoginService.loginAuth(LoginService.java:37) ~[classes/:na]
	at com.cloud.cola.adapter.LoginController.login(LoginController.java:34) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]

**Comment by newAndroier** [comment]
请问，这个【实现多扩展点，找不到实现方法】问题解决了吗？我也遇到这个问题。我的cola版本用的3.1.0，扩展类获取不到，ExtensionExecutor.extensionRepository.extensionRepo是个空Map。

**Comment by zhao-staff-officer** [comment]
> 请问，这个【实现多扩展点，找不到实现方法】问题解决了吗？我也遇到这个问题。我的cola版本用的3.1.0，扩展类获取不到，ExtensionExecutor.extensionRepository.extensionRepo是个空Map。

debug源码，当前@extension实现类，容器里面只有一个映射关系。所以第二个方法找不到。感觉算是BUG。要么设计开始就不允许这么写，一个扩展类只允许实现一个扩展点。要么等修复这个问题。或者PR一下。

**Comment by newAndroier** [comment]
> 

这个问题我解决了，
1. 首先要在Application的@SpringBootApplication注解里引入"com.alibaba.cola"。但是我引入这个包会跟我项目里的ApplicationContextHelper冲突。所以只引入"com.alibaba.cola.extension".
2. 但是不引入com.alibaba.cola.core的话， SpringBootstrap类里的init()方法就没有执行，导致扩展点没有加载进来。
3. 所以我把init()方法，及其调用的方法拿出来重写了。然后就能引入扩展类了。而且是能够引入多个扩展类。你可以试一试

**Comment by significantfrank** [comment]
> > 请问，这个【实现多扩展点，找不到实现方法】问题解决了吗？我也遇到这个问题。我的cola版本用的3.1.0，扩展类获取不到，ExtensionExecutor.extensionRepository.extensionRepo是个空Map。
> 
> debug源码，当前@extension实现类，容器里面只有一个映射关系。所以第二个方法找不到。感觉算是BUG。要么设计开始就不允许这么写，一个扩展类只允许实现一个扩展点。要么等修复这个问题。或者PR一下。

Cola-extension的确没有考虑到这个多扩展点的情况，你可以提一个PR增强一下
