### ISSUE TITLE
采用mvn install打包后，执行jar文件报错

### ISSUE THREAD

**Issue by fasimito** [alibaba/COLA#279]
mvn install打包，jar文件生成，但是出现
D:\workspaces\istio-demo\start\target>java -jar start-1.0.0-SNAPSHOT.jar
start-1.0.0-SNAPSHOT.jar中没有主清单属性
这个错误
手动指定Main入口又出现下面错误
D:\workspaces\istio-demo\start\target>java -cp start-1.0.0-SNAPSHOT.jar com.cola.istio.demo.Application
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
        at com.cola.istio.demo.Application.main(Application.java:17)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more

我本地的JDK环境是：
D:\workspaces\app1\target>java --version
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

不知道这个东西还有多少坑。

**Comment by liuzhaowei55** [comment]
start 添加 plugin
```xml
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
```
