### ISSUE TITLE
when  AOP use JdkDynamicAopProxy, startup NullPointerException

### ISSUE THREAD

**Issue by hnxiaoyuan** [alibaba/COLA#327]
项目中启动报错，发现如下异常，debug跟踪发现AOP使用JdkDynamicAopProxy时，会出现此异常，使用CGLIB代理时使用正常，已提交一个小PR修复此问题，麻烦大佬看看，谢谢.

```java
Caused by: java.lang.NullPointerException: null
	at com.alibaba.cola.extension.register.ExtensionRegister.doRegistration(ExtensionRegister.java:38) ~[cola-component-extension-starter-4.3.1.jar:na]
	at com.alibaba.cola.extension.register.ExtensionBootstrap.lambda$init$0(ExtensionBootstrap.java:32) ~[cola-component-extension-starter-4.3.1.jar:na]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_331]
	at com.alibaba.cola.extension.register.ExtensionBootstrap.init(ExtensionBootstrap.java:31) ~[cola-component-extension-starter-4.3.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_331]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_331]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_331]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_331]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.2.jar:5.3.2]
	at
```

**Comment by hnxiaoyuan** [comment]
> 启动类加 `@EnableAspectJAutoProxy(exposeProxy=true)` 试试

@heihei180 老兄，我说的是一种场景下的问题呢，我知道在使用CGLIB代理的情况下没有问题呢，测试过。

**Comment by wyyl1** [comment]
看标题我还以为是一位外国友人遇到了问题
