### ISSUE TITLE
BizScenario must implement java.io.Serializable

### ISSUE THREAD

**Issue by qq240996777** [alibaba/COLA#58]
在集成dubbo的时候，扩展类没有实现序列化

`Caused by: java.lang.RuntimeException: Serialized class com.alibaba.cola.extension.BizScenario must implement java.io.Serializable
 Java field: private com.alibaba.cola.extension.BizScenario com.alibaba.cola.dto.Command.bizScenario
	at com.alibaba.com.caucho.hessian.io.JavaSerializer$FieldSerializer.serialize(JavaSerializer.java:299)
	at com.alibaba.com.caucho.hessian.io.JavaSerializer.writeInstance(JavaSerializer.java:279)
	at com.alibaba.com.caucho.hessian.io.JavaSerializer.writeObject(JavaSerializer.java:246)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:383)
	at com.alibaba.dubbo.common.serialize.support.hessian.Hessian2ObjectOutput.writeObject(Hessian2ObjectOutput.java:77)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.encodeRequestData(DubboCodec.java:175)
	at c`

**Comment by significantfrank** [comment]
提一个PR吧

**Comment by lifesign** [comment]
+1 遇到了这个问题 BizScenario 这么重要的属性 没有经过测试吗？
